[build-system]
requires = ["hatchling"]
build-backend = "hatchling.build"

[project]
name = "Ars-Mediaevalis"
version = "0.1.0"
description = "A medieval and renaissance art history wallpaper tool for hyprland and noctalia."
readme = "README.md"
license = "MIT"
license-files = ["LICENSE"]
requires-python = ">=3.12"
dependencies = [
    "httpx>=0.28.1",
    "pillow>=10",
    "pygobject>=3.50",
]

[project.scripts]
ars_mediaevalis = "ars_mediaevalis.cli:main"

[tool.hatch.build.targets.wheel]
packages = ["src/ars_mediaevalis"]
